version: '3.3'

volumes:
    worker_node_modules:

services:
  worker:
    image: build_container
    volumes:
      - ..:/app
      - worker_node_modules:/data/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    working_dir: /app
