apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "backend-api.selectorLabels" . | nindent 4 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.metadata.annotations | nindent 8 }}
      labels:
        {{- include "backend-api.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.metadata.labels | nindent 8 }}

    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

