{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  path: /
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.containerPort }}
{{- end }}