apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "backend-api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}   
      targetPort: {{ .Values.containerPort }} 
